
export const CREEP_NEWEDIT = {
  name: "New Creature",
  size: "Medium",
  type: "Type",
  subtype: null,
  alignment: null,
  armor_class: 10,
  hit_points: 1,
  hit_dice: null,
  speed: "25",
  strength: 10,
  dexterity: 10,
  constitution: 10,
  intelligence: 10,
  wisdom: 10,
  charisma: 10,
  damage_vulnerabilities: null,
  damage_resistances: null,
  damage_immunities: null,
  condition_immunities: null,
  senses: null,
  languages: null,
  challenge_rating: null,
  special_abilities: null,
  actions: null
}
